[40기-윤형준 | 임다슬] 1st project: initial-setting
wecode-bootcamp-korea/40-1st-weKea-backend pull request #1
Opened 2022-12-05 15:18 UTC by hysy9255

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- Initial setting
- signup/signin API 구현
- migration file 추가 완료

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성

<br />

## :: 테스트 결과 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2022-12-07 01:50 UTC, sangwoong03 requested changes
형준님 다슬님 고생하셨습니다!

다만 현재 초기세팅 부분에 Layered Pattern이 적용되어 있지 않는데요,
이번 리뷰를 반영하면서 Layered Pattern을 적용하여 수정해주시면 되겠습니다!

이해가 잘 가지 않는 부분에 대해서는 커멘트 달아주세요!

2022-12-07 01:50 UTC, sangwoong03 commented on app.js
> +});
해당 부분은 로그인 및 회원가입 기능으로 초기세팅이라는 PR과 맞지 않는 기능인 것 같습니다.

다른 PR에 작성할 수 있도록 수정해주세요!

2022-12-07 01:50 UTC, sangwoong03 commented on db/migrations/20221205161456_users.sql
> +);
전반적인 들여쓰기 (Indentation)를 수정하여 코드의 가독성을 높여주세요~!
- id 컬럼에 PRIMARY KEY 속성을 지정하는 경우 아래 코드와 같이 작성할 수도 있습니다. 참고해주세요~!
- date_of_birth 컬럼은 birhdate 로 컬럼명을 수정해도 좋을 것 같습니다!
- email 컬럼의 최대 길이를 수정하는 것이 좋을 것 같습니다! 이메일의 최대 길이에 대한 자료를 찾아보고 적용해주세요!
- bcrypt를 활용하여 비밀번호를 암호화하는 경우 반환되는 데이터 타입과 최대 길이를 찾아보고 적용해주세요!

```suggestion
CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    last_name VARCHAR(50) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    birthdate VARCHAR(50) NOT NULL,
    phone_number VARCHAR(50) NOT NULL,
    gender VARCHAR(50) NOT NULL,
    address VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password BINARY(60) NOT NULL,
    point DECIMAL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT users_email_ukey UNIQUE (email),
);
```

2022-12-07 01:50 UTC, sangwoong03 commented on db/migrations/20221206102052_categories.sql
> +		PRIMARY KEY(id)
들여쓰기 수정해주세요!

2022-12-07 01:50 UTC, sangwoong03 commented on db/migrations/20221206102058_products.sql
> +		PRIMARY KEY(id),
들여쓰기 수정 혹은 id 컬럼에 바로 지정해주세요!

2022-12-07 01:50 UTC, sangwoong03 commented on db/migrations/20221206102109_product_images.sql
> +);
들여쓰기 수정해주세요!

2022-12-07 01:50 UTC, sangwoong03 commented on db/migrations/20221206102114_carts.sql
> +		PRIMARY KEY(id),
들여쓰기 수정 혹은 id 컬럼에 바로 지정해주세요!

2022-12-07 01:50 UTC, sangwoong03 commented on package.json
> +    "dbmate": "^1.0.3",
npm으로 설치한 dbmate는 현재 프로젝트 개발에 있어 사용하지 않는 모듈입니다.

우리가 사용하는 dbmate는 전역으로 설치하여 로컬 데이터베이스에 스키마를 생성하기 위한 클라이언트입니다.

두가지를 혼동하지 않도록 유의해주시고, npm uninstall dbmate를 통해 설치된 모듈을 삭제해주세요!

2022-12-07 01:50 UTC, sangwoong03 commented on db/migrations/20221206102058_products.sql
> +    category_id int,
NULL 허용 여부를 지정해주세요!

2022-12-07 06:38 UTC, hysy9255 commented
**Note!**

DB migration file에서  Foreign Key로 설정되어 있는 column NOT NULL로 설정해야함.

2022-12-09 05:17 UTC, sangwoong03 requested changes
고생하셨습니다.

레이어드 패턴도 적용 잘 해주셨습니다.

수정 사항 반영해주시고, 다음 작업부터는 브랜치 네이밍 컨벤션에 맞게 브랜치명 만들어서 작업해주세요~!
- `feature/product-lists` - 기능 추가
- `fix/signin` - 기능 수정

2022-12-09 05:17 UTC, sangwoong03 commented on .env.sample
> +TYPEORM_CONNECTION = RMDBS_TYPE
오탈자가 있네요!

2022-12-09 05:17 UTC, sangwoong03 commented on db/migrations/20221205161456_users.sql
> +	date_of_birth VARCHAR(50) NOT NULL,
컬럼명 `birthdate`로 수정하는 것이 더 명확할 것 같습니다!

2022-12-09 05:17 UTC, sangwoong03 commented on db/migrations/20221205161456_users.sql
> +	email VARCHAR(50) NOT NULL,
email이 아무리 길어도 50자는 되지는 않겠지만 이메일 username으로 최대 64글자, domain으로 최대 255글자, @ 1글자로 최대 320자로 설정해도 좋을 것 같습니다~!

2022-12-09 05:17 UTC, sangwoong03 commented on db/migrations/20221206102058_products.sql
> +  rating int,
rating시 소수점을 고려한다면 float 필드로 수정하는 것이 좋아보입니다!

2022-12-09 05:17 UTC, sangwoong03 commented on src/routes/auth.router.js
> +});
불필요한 코드인 것 같습니다. 삭제해주세요~!

2022-12-09 05:17 UTC, sangwoong03 commented on src/services/auth.service.js
> +  dateOfBirth,
컬럼명을 변경하면서 birthdate로 받아와도 될 것 같습니다!

2022-12-09 05:17 UTC, sangwoong03 commented on src/services/auth.service.js
> +  if (user === undefined) {
`user === undefined` 는 다음 표현식으로 대체할 수 있습니다!
```suggestion
  if (!user) {
```

2022-12-09 05:17 UTC, sangwoong03 commented on src/controllers/auth.controller.js
> +    req.body;
해당 필수 데이터 중 하나라도 들어오지 않으면 `key error`를 반환할 수 있도록 예외처리를 해주세요

2022-12-09 05:17 UTC, sangwoong03 commented on src/controllers/auth.controller.js
> +  res.status(201).end();
데이터가 생성된 결과를 statusCode로 전달해도 충분하겠지만, 클라이언트에게 명확한 메시지를 던져도 좋을 것 같습니다!

```suggestion
  res.status(201).json({ message: "success" });
```

2022-12-09 05:17 UTC, sangwoong03 commented on src/controllers/auth.controller.js
> +  const { email, password } = req.body;
해당 부분도 마찬가지로 필수 데이터가 들어오지 않았을 때 `key error`를 반환할 수 있는 예외처리를 추가해주세요!

2022-12-09 05:17 UTC, sangwoong03 commented on src/services/auth.service.js
> +  }
로컬에서만 확인할 수 있는 로그가 아닌, 클라이언트가 확인할 수 있는 메시지를 던져주어야 할 것 같습니다!

`try { ... } catch(err) { ... }` 구문을 사용할 수 있을 것 같습니다!

2022-12-09 05:17 UTC, sangwoong03 commented on src/services/auth.service.js
> +};
```suggestion
const signIn = async (email, password) => {
  const user = await userDao.getUserByEmail(email);
  // 1
  if (!user) {
    throw new Error("NONEXISTENT_USER");
  }
  
  //2
  const isMatch = await bcrypt.compare(password, user.password);
  if (!isMatch) {
    throw new Error("INVALID_USER")
  }
  
  // 3
  const SSECRET_KEY = process.env.SECRETE_KEY;
  // 4
  const jwtToken = jwt.sign({ userId: user.id }, secretKey. {
      expireseIn: '9d'
  });
    
  return jwtToken
};
```

1. user 조회 후 user가 존재하지 않을 경우의 예외처리가 필요해보입니다!
2. 변수명을 좀 더 명확하게 수정 후, 비밀번호가 일치하지 않은 경우의 예외처리를 추가해주어야 합니다!
3. `secret key`는 상수 데이터로 변수 네이밍 컨벤션을 따라 변수명을 수정해주세요!
4. `token`의 페이로드 데이터로 유저의 정보와 토큰 발급 시간을 주입해주셨는데, 주입 시간은 토큰을 발급하는 그 시점에 자동으로 생성되며, 만약 만료기간을 고려하신 것이라면 3번째 인수로 받는 객체의 프로퍼티인 `expirseIn`에 대한 값을 설정해주면 됩니다. 공식문서를 확인하여 사용법을 확인해보고, 민감한 데이터라면 환경변수로 관리할 수 있을 것 같습니다~!

2022-12-09 05:17 UTC, sangwoong03 commented on db/migrations/20221205161456_users.sql
> +	birth_date VARCHAR(50) NOT NULL,
컬럼명을  `birthdate`로 수정하는 것이 더 명확해보입니다~!

2022-12-09 05:17 UTC, sangwoong03 commented on src/models/user.dao.js
> +  `,
특정 유저의 모든 데이터를 조회하기 보다는 해당 로직에 필요한 컬럼만 조회하는 것이 더 나은 성능을 보일 수 있을 것 같습니다.

```suggestion
    `
    SELECT
      u.id,
      u.name,
      u.email,
      u.password
    FROM users u
    WHERE u.email = ?
  `,
```

2022-12-09 08:56 UTC, hysy9255 commented on .env.sample
> +TYPEORM_CONNECTION = RMDBS_TYPE
오탈자가 무슨 말씀이시죠?

2022-12-11 07:51 UTC, sangwoong03 requested changes
중간중간 수정이 덜 된 부분이 있는 것 같습니다!
확인 후 다시 수정해주세요 형준님!

2022-12-11 07:51 UTC, sangwoong03 commented on db/migrations/20221205161456_users.sql
> +	phoneNumber VARCHAR(50) NOT NULL,
데이터베이스의 컬럼명을 설정할 때엔 snake-case 혹은 camelCase 둘중 하나로 통일해주세요!
다른 컬럼들의 경우 snake_case로 컬럼명으로 설정되어있네요!

`phone_number` 혹은 `phonenumber` 정도로 수정하시면 될 것 같습니다.

2022-12-11 07:51 UTC, sangwoong03 commented on src/controllers/auth.controller.js
> +};
회원가입 기능을 구현하기 위해 반드시 필요한 데이터가 없는 경우 발생하는 에러에 대한 예외처리를 적용해주세요!

2022-12-11 07:51 UTC, sangwoong03 commented on src/controllers/auth.controller.js
> +};
해당 부분도 마찬가지입니다.
아래 예시 코드를 참고하여 적용해주세요!

```suggestion
const signIn = async (req, res) => {
  try {
    const { email, password } = req.body;
   
   if(!email || !password) {
     throw new Error("key error");
   }
   
    const accessToken = await authService.signIn(email, password);
    
    res.status(200).json({ accessToken: accessToken });
  } catch (err) {
    res.status(err.statusCode || 401).json({ message: err.message });
  }
};
```

2022-12-11 07:51 UTC, sangwoong03 commented on src/services/auth.service.js
> +  }
다음과 같이 조건문 내부의 조건을 더욱 줄여서 사용할 수 있습니다.
그리고 회원가입이니 email이 있다는 메시지를 반환하기 보단 해당 이메일을 가진 유저가 있다는 것을 보여주는 것이 좋아보입니다.

만약 이메일 중복을 방지하기 위해서는 `user.email`이 input으로 받은 email 데이터와 일치하는지 확인할 필요가 있을 것 같습니다!

```suggestion
  if (user) {
    throw new Error("USER_ALREADY_EXIST");
  }
```

2022-12-11 07:51 UTC, sangwoong03 commented on src/services/auth.service.js
> +  console.log(jwtToken);
토큰을 확인하는 콘솔은 불필요해보이니 삭제해주세요~!

2022-12-12 09:11 UTC, hysy9255 commented on src/controllers/auth.controller.js
> +};
꼼꼼하게 리뷰 해주셔서 더 많이 배우는 것 같습니다~!

2022-12-12 23:58 UTC, sangwoong03 requested changes

2022-12-12 23:58 UTC, sangwoong03 commented on src/controllers/auth.controller.js
> +    } else {
이 로직 커멘트로 설명부탁드립니다~!

2022-12-13 02:19 UTC, hysy9255 commented on src/controllers/auth.controller.js
> +    } else {
request body에는 회원이 입력한 회원 정보가 담겨 있습니다.  이 회원 정보를 분해 할당하고 할당된 변수들을 userInformation이라는 배열 안에 넣습니다. 그리고 if 절을 통해 분해 할당된 변수들 중 하나라도 undefined가 있는지 배열의 includes라는 메서드를 통해 확인합니다. 만약 undefiend 가 존재한다면 에러 메세지를 띄우고 그렇지 않다면 signUp을 진행합니다.

2022-12-13 05:54 UTC, sangwoong03 approved these changes
LGTM 👍

2022-12-13 05:55 UTC, merged